# OA管理項目配置文件

OaDictURL = "/camel/rest/oa/dicts"
OaDictsTypesListURL = "/camel/rest/oa/dicts/types/list"
CategoryURL = "/camel/rest/categorys"
WorkflowURL = "/camel/rest/workflow"
WorkflowSuspendURL = "/camel/rest/workflow/suspend?key="
WorkflowActivateURL = "/camel/rest/workflow/activate?key="
WorkflowHistoryURL = "/camel/rest/workflow/historys"
MyInvolvedURL = "/camel/rest/workflow/myInvolvedHistory"
MyHistoryURL = "/camel/rest/workflow/myHistory"

# 需要自动注册成全局的Category组件
[[OaCategoryComponent]]
  path = "./categoryView.vue"
  name = "OaCategoryView"
[[OaCategoryComponent]]
  path = "./categoryAdd"
  name = "OaCategoryAdd"
[[OaCategoryComponent]]
  path = "./categorySearch"
  name = "OaCategorySearch"

# workflow 的全局注册组件
[[OaWorkflowComponent]]
  path = "./processHistorySearch.vue"
  name = "OaProcessHistorySearch"
[[OaWorkflowComponent]]
  path = "./processHistoryView.vue"
  name = "OaProcessHistoryView"
[[OaWorkflowComponent]]
  path = "./processDefinitionView.vue"
  name = "OaProcessDefinitionView"

# workflow 的默认按钮定义
[[WorkflowButtonList]]
  id = "view"
  title = "查看"
  isShow = true    # 是否显示
  isPermission = true   # 是否进行权限认证

# ProcessDefinition 的默认按钮定义
[[ProcessDefinitionButtonList]]
  id = "view"
  title = "查看"
  isShow = true    # 是否显示
  isPermission = true   # 是否进行权限认证
[[ProcessDefinitionButtonList]]
  id = "suspend"
  title = "无效"
  isShow = true    # 是否显示
  isPermission = true   # 是否进行权限认证

# table 的默认按钮定义
[[ToolButtonList]]
  id = "view"
  title = "查看"
  isShow = true    # 是否显示
  isPermission = true   # 是否进行权限认证
[[ToolButtonList]]
  id = "edit"
  title = "编辑"
  isShow = true
  isPermission = true
[[ToolButtonList]]
  id = "delete"
  title = "删除"
  isShow = true
  isPermission = true
