# OA管理項目配置文件

OaDictURL = "/camel/rest/oa/dicts"
OaDictsTypesListURL = "/camel/rest/oa/dicts/types/list"
CategoryURL = "camel/rest/categorys"

# 需要自动注册成全局的Category组件
[[OaCategoryComponent]]
  path = "./categoryView.vue"
  name = "OaCategoryView"
[[OaCategoryComponent]]
  path = "./categoryAdd"
  name = "OaCategoryAdd"
[[OaCategoryComponent]]
  path = "./categorySearch"
  name = "OaCategorySearch"


# table 的默认按钮定义
[[ToolButtonList]]
  id = "view"
  title = "查看"
  isShow = true    # 是否显示
  isPermission = true   # 是否进行权限认证
[[ToolButtonList]]
  id = "edit"
  title = "编辑"
  isShow = true
  isPermission = true
[[ToolButtonList]]
  id = "delete"
  title = "删除"
  isShow = true
  isPermission = true
