# OA管理項目配置文件

OaDictURL = "/camel/rest/oa/dicts"
OaDictsTypesListURL = "/camel/rest/oa/dicts/types/list"
CategoryURL = "/camel/rest/categorys"
WorkflowURL = "/camel/rest/workflow"
WorkflowSuspendURL = "/camel/rest/workflow/suspend?key="
WorkflowActivateURL = "/camel/rest/workflow/activate?key="
WorkflowMainWorkURL = "/camel/rest/categorys/getAll"
WorkflowHistoryURL = "/camel/rest/workflow/historys"
MyInvolvedURL = "/camel/rest/workflow/myInvolvedHistory"
MyHistoryURL = "/camel/rest/workflow/myHistory"
TaskURL = "/camel/rest/workflow/tasks"

# 工作流流程地址
MeetingApplyURL = "/camel/rest/meetingapplys"
UserOrgsURL = "/camel/rest/users/[usersId]/orgs"
MeetingRoomsURL  = "/camel/rest/meetingrooms"




# 需要自动注册成全局的Category组件
[[OaCategoryComponent]]
  path = "oa/category/categoryView"
  name = "OaCategoryView"
[[OaCategoryComponent]]
  path = "oa/category/categoryAdd"
  name = "OaCategoryAdd"
[[OaCategoryComponent]]
  path = "oa/category/categorySearch"
  name = "OaCategorySearch"

# 需要自动注册成全局的MeetingApply组件
[[MeetingApplyComponent]]
  path = "oa/meetingapply/meetingApplyView"
  name = "OaMeetingApplyView"
[[MeetingApplyComponent]]
  path = "oa/meetingapply/meetingApplyAdd"
  name = "OaMeetingApplyAdd"
[[MeetingApplyComponent]]
  path = "oa/meetingapply/meetingApplySearch"
  name = "OaMeetingApplySearch"

# workflow 的全局注册组件
[[OaWorkflowComponent]]
  path = "oa/comp/processHistorySearch"
  name = "OaProcessHistorySearch"
[[OaWorkflowComponent]]
  path = "oa/comp/processHistoryView"
  name = "OaProcessHistoryView"
[[OaWorkflowComponent]]
  path = "oa/comp/processDefinitionView"
  name = "OaProcessDefinitionView"
[[OaWorkflowComponent]]
  path = "oa/comp/taskView"
  name = "OaTaskView"
[[OaWorkflowComponent]]
  path = "oa/comp/taskComplete"
  name = "OaTaskComplete"

# workflow 的默认按钮定义
[[WorkflowButtonList]]
  id = "view"
  title = "查看"
  isShow = true    # 是否显示
  isPermission = true   # 是否进行权限认证

# ProcessDefinition 的默认按钮定义
[[ProcessDefinitionButtonList]]
  id = "view"
  title = "查看"
  isShow = true    # 是否显示
  isPermission = true   # 是否进行权限认证
[[ProcessDefinitionButtonList]]
  id = "suspend"
  title = "scope.suspensionState === 1 ? '运行' : '停止'"
  isShow = true    # 是否显示
  isPermission = true   # 是否进行权限认证

# table 的默认按钮定义
[[ToolButtonList]]
  id = "view"
  title = "查看"
  isShow = true    # 是否显示
  isPermission = true   # 是否进行权限认证
[[ToolButtonList]]
  id = "edit"
  title = "编辑"
  isShow = true
  isPermission = true
[[ToolButtonList]]
  id = "delete"
  title = "删除"
  isShow = true
  isPermission = true

# 工作流的默认按钮定义
[[WorkflowToolButtonList]]
  id = "view"
  title = "查看"
  isShow = true    # 是否显示
  isPermission = true   # 是否进行权限认证
[[WorkflowToolButtonList]]
  id = "edit"
  title = "编辑"
  isShow = true
  isPermission = true
[[WorkflowToolButtonList]]
  id = "delete"
  title = "删除"
  isShow = true
  isPermission = true
[[WorkflowToolButtonList]]
  id = "attachment"
  title = "附件"
  isShow = true
  isPermission = true
[[WorkflowToolButtonList]]
  id = "start"
  title = "启动"
  isShow = true
  isPermission = true
