# 科研管理項目配置文件

ResearchDictsURL = "/camel/rest/research/dicts"
ResearchDictsTypesListURL = "/camel/rest/research/dicts/types/list"
TeacherURL = "/camel/rest/teachers"
StudentURL = "/camel/rest/students"
MajorCourseURL = "/camel/rest/majorcourses"
WorkerURL = "/camel/rest/workers"
CompetitionInfoURL = "/camel/rest/competitionInfos"
SignupURL = "/camel/rest/signups"
signupBtnPermissionPrefix = "research:researchCompetitionModule:competitionSigninMenu:"
competitBtnPermissionPrefix = "research:researchCompetitionModule:competitionInfoMenu:"
awardBtnPermissionPrefix = "research:researchCompetitionModule:competitionAwardMenu:"
AwardURL = "/camel/rest/awards"
StatisticsPieURL = "/camel/rest/competitioninfos/statistics"

ResearchCacheKey = "RESEARCH-DICT-KEY"

# 需要自动注册成全局的Teacher组件
[[TeacherComponent]]
  path = "research/teacher/teacherView"
  name = "ResearchTeacherView"
[[TeacherComponent]]
  path = "research/teacher/teacherAdd"
  name = "ResearchTeacherAdd"
[[TeacherComponent]]
  path = "research/teacher/teacherSearch"
  name = "ResearchTeacherSearch"

# 需要自动注册成全局的Worker组件
[[WorkerComponent]]
  path = "research/worker/workerView"
  name = "ResearchWorkerView"
[[WorkerComponent]]
  path = "research/worker/workerAdd"
  name = "ResearchWorkerAdd"
[[WorkerComponent]]
  path = "research/worker/workerSearch"
  name = "ResearchWorkerSearch"

# 需要自动注册成全局的Student组件
[[ResearchStudentComponent]]
  path = "research/student/studentView"
  name = "ResearchStudentView"
[[ResearchStudentComponent]]
  path = "research/student/studentAdd"
  name = "ResearchStudentAdd"
[[ResearchStudentComponent]]
  path = "research/student/studentSearch"
  name = "ResearchStudentSearch"
[[ResearchStudentComponent]]
  path = "research/student/scoreAdd"
  name = "ResearchScoreAdd"
[[ResearchStudentComponent]]
  path = "research/student/scoreSearch"
  name = "ResearchScoreSearch"

# 需要自动注册成全局的CompetitionInfo组件
[[CompetitionInfoComponent]]
  path = "research/competitioninfo/competitioninfoView"
  name = "ResearchCompetitionInfoView"
[[CompetitionInfoComponent]]
  path = "research/competitioninfo/competitioninfoAdd"
  name = "ResearchCompetitionInfoAdd"
[[CompetitionInfoComponent]]
  path = "research/competitioninfo/competitioninfoSearch"
  name = "ResearchCompetitionInfoSearch"

# 需要自动注册成全局的Signup组件
  [[SignupComponent]]
    path = "research/signup/signupView"
    name = "ResearchSignupView"
  [[SignupComponent]]
    path = "research/signup/signupAdd"
    name = "ResearchSignupAdd"
  [[SignupComponent]]
    path = "research/signup/signupSearch"
    name = "ResearchSignupSearch"

# 需要自动注册成全局的Award组件
  [[AwardComponent]]
    path = "research/award/awardView"
    name = "ResearchAwardView"
  [[AwardComponent]]
    path = "research/award/awardAdd"
    name = "ResearchAwardAdd"
  [[AwardComponent]]
    path = "research/award/awardSearch"
    name = "ResearchAwardSearch"

# table 的默认按钮定义
[[ToolButtonList]]
  id = "view"
  title = "查看"
  isShow = true    # 是否显示
  isPermission = true   # 是否进行权限认证
[[ToolButtonList]]
  id = "edit"
  title = "编辑"
  isShow = true
  isPermission = true
[[ToolButtonList]]
  id = "delete"
  title = "删除"
  isShow = true
  isPermission = true
[[ToolButtonList]]
  id = "attachment"
  title = "附件"
  isShow = true
  isPermission = true

# table 使用的按钮定义
[[ToolButtonPersonList]]
  id = "view"
  title = "查看"
  isShow = true    # 是否显示
  isPermission = true   # 是否进行权限认证
[[ToolButtonPersonList]]
  id = "newEdit"
  title = "编辑"
  isShow = true
  isPermission = true

# table-score 使用的按钮定义
[[ToolButtonScoreList]]
  id = "newEdit"
  title = "编辑"
  isShow = true
  isPermission = true
[[ToolButtonScoreList]]
  id = "delete"
  title = "删除"
  isShow = true
  isPermission = true
