# 科研管理項目配置文件

ResearchDictsURL = "/camel/rest/research/dicts"
ResearchDictsTypesListURL = "/camel/rest/research/dicts/types/list"
TeacherURL = "/camel/rest/teachers"
StudentURL = "/camel/rest/students"
WorkerURL = "/camel/rest/workers"

# 需要自动注册成全局的Teacher组件
[[TeacherComponent]]
  path = "./teacherView"
  name = "ResearchTeacherView"
[[TeacherComponent]]
  path = "./teacherAdd"
  name = "ResearchTeacherAdd"
[[TeacherComponent]]
  path = "./teacherSearch"
  name = "ResearchTeacherSearch"

# 需要自动注册成全局的Worker组件
[[WorkerComponent]]
  path = "./workerView"
  name = "ResearchWorkerView"
[[WorkerComponent]]
  path = "./workerAdd"
  name = "ResearchWorkerAdd"
[[WorkerComponent]]
  path = "./workerSearch"
  name = "ResearchWorkerSearch"

# table 的默认按钮定义
[[ToolButtonList]]
  id = "view"
  title = "查看"
  isShow = true    # 是否显示
  isPermission = true   # 是否进行权限认证
[[ToolButtonList]]
  id = "edit"
  title = "编辑"
  isShow = true
  isPermission = true
[[ToolButtonList]]
  id = "delete"
  title = "删除"
  isShow = true
  isPermission = true
