# 科研管理項目配置文件

CommonDictsURL = "/camel/rest/common/dicts"
NewsURL = "/camel/rest/newss"
NoteURL = "/camel/rest/notes"

# 需要自动注册成全局的News组件
[[NewsComponent]]
  path = "./newsView"
  name = "CommonNewsView"
[[NewsComponent]]
  path = "./newsAdd"
  name = "CommonNewsAdd"
[[NewsComponent]]
  path = "./newsSearch"
  name = "CommonNewsSearch"

# 需要自动注册成全局的Note组件
[[NoteComponent]]
  path = "./noteView"
  name = "CommonNoteView"
[[NoteComponent]]
  path = "./noteAdd"
  name = "CommonNoteAdd"
[[NoteComponent]]
  path = "./noteSearch"
  name = "CommonNoteSearch"

# table 的默认按钮定义
[[ToolButtonList]]
  id = "view"
  title = "查看"
  isShow = true    # 是否显示
  isPermission = true   # 是否进行权限认证
[[ToolButtonList]]
  id = "edit"
  title = "编辑"
  isShow = true
  isPermission = true
[[ToolButtonList]]
  id = "delete"
  title = "删除"
  isShow = true
  isPermission = true
