cacheTime = 7200000 #缓存校验时间
baseURL = "http://localhost:8181"
loginUrl = "/login.jsp"
logoutUrl = "/logout"
applicationURL = "/camel/rest/system/applications"
usersURL = "/camel/rest/users"

ScheduleDictsURL = "/camel/rest/schedule/dicts"
ScheduleDictsTypesListURL = "/camel/rest/schedule/dicts/types/list"

[systemApplications]
admin = "/camel/rest/system/applications/admin"
common = "/camel/rest/system/applications/common"
oa = "/camel/rest/system/applications/oa"
schedule = "/camel/rest/system/applications/schedule"

[PageConfig]
  sizes = [20, 30, 40]
  limit = 0
  page = 1
  start = 0
