# 系统管理項目配置文件

AdminDictURL = "/camel/rest/admin/dicts"
AdminDictsTypesListURL = "/camel/rest/admin/dicts/types/list"

usersURL = "/camel/rest/users"
appsURL = "/camel/rest/system/applications"
workgroupURL = "/camel/rest/workgroups"
userBtnPermissionPrefix = "admin:permissionModule:userMenu:"
workGroupBtnPermissionPrefix = "admin:permissionModule:workGroupMenu:"

# table 的默认按钮定义
[[ToolButtonList]]
  id = "view"
  title = "查看"
  isShow = true    # 是否显示
  isPermission = true   # 是否进行权限认证
[[ToolButtonList]]
  id = "edit"
  title = "编辑"
  isShow = true
  isPermission = true
[[ToolButtonList]]
  id = "delete"
  title = "删除"
  isShow = true
  isPermission = true

[[WorkGroupComponent]]
 path = "admin/workgroup/workgroupView"
 name = "AdminWorkGroupView"
[[WorkGroupComponent]]
 path = "admin/workgroup/workgroupAdd"
 name = "AdminWorkGroupAdd"
[[WorkGroupComponent]]
 path = "admin/workgroup/workgroupSearch"
 name = "AdminWorkGroupSearch"

[[UserComponent]]
 path = "admin/user/userEdit"
 name = "AdminUserEdit"
[[UserComponent]]
 path = "admin/user/userAdd"
 name = "AdminUserAdd"
[[UserComponent]]
 path = "admin/user/userSearch"
 name = "AdminUserSearch"
