# 计划任务項目配置文件

ResearchDictsURL = "/camel/rest/research/dicts"
TeacherURL = "/camel/rest/teachers"
StudentURL = "/camel/rest/students"
WorkerURL = "/camel/rest/workers"
## 字典管理
ScheduleDictsURL = "/camel/rest/schedule/dicts"
ScheduleDictsTypesListURL = "/camel/rest/schedule/dicts/types/list"

# 需要自动注册成全局的 ScheduleDict 组件
[[ScheduleDictsComponent]]
  path = "./scheduledictView"
  name = "ResearchScheduleDictView"
[[ScheduleDictsComponent]]
  path = "./scheduledictAdd"
  name = "ResearchScheduleDictAdd"
[[ScheduleDictsComponent]]
  path = "./scheduledictSearch"
  name = "ResearchScheduleDictSearch"

# table 的默认按钮定义
[[ToolButtonList]]
  id = "view"
  title = "查看"
  isShow = true    # 是否显示
  isPermission = true   # 是否进行权限认证
[[ToolButtonList]]
  id = "edit"
  title = "编辑"
  isShow = true
  isPermission = true
[[ToolButtonList]]
  id = "delete"
  title = "删除"
  isShow = true
  isPermission = true
[[ToolButtonList]]
  id = "attachment"
  title = "上传附件"
  isShow = true
  isPermission = true
