[FormModel]
  name = ""
  type = ""
  address = ""
  collectionStartTime = ""
  collectionEndTime = ""
  preEvalStartTime = ""
  preEvalEndTime = ""
  lastEvalStartTime = ""
  lastEvalEndTime = ""
  compStartTime = ""
  compEndTime = ""
  contentNeed = ""
  technologyNeed = ""
  contactor = ""
  phone = ""
  email = ""
  signupStyle = ""
  detail = ""
  remark = ""
